#! /usr/bin/env ruby
require 'pg'
require 'pry'

DATABASE_NAME = 'expense'


def valid_amount?(amount)
  amount.match?(/^[0-9]{1,4}\.[0-9]{1,2}$/)
end

def valid_memo?(memo)
  memo.match?(/^[a-zA-Z]+ ?[a-zA-Z]+$/)
end

def convert_amount_argument_to_string(amount_argument)
  amount_argument.join(" ")
end

def add_new_expense
  db = connect_to_database

  amount = ARGV[1]
  memo = convert_amount_argument_to_string(ARGV[2..])

  if valid_amount?(amount) && valid_memo?(memo)
    query = "INSERT INTO expenses (amount, memo, created_on) VALUES ($1, $2, $3);"
    params = ["#{amount}", "#{memo}", "NOW()"]

    db.exec_params(query, params)
    puts "The expense has been added successfully."
  else
    puts "You must provide an valid amount and a valid memo."
  end

end

class ExpenseManager
  def initialize
    @db = connect_to_database
  end

  def list_expenses
    read_expenses
  end

  def display_help
    puts <<~HELP
  An expense recording system

  Commands:

  add AMOUNT MEMO - record a new expense
  clear - delete all expenses
  list - list all expenses
  delete NUMBER - remove expense with id NUMBER
  search QUERY - list expenses with a matching memo field
  HELP
  end

  private

  def connect_to_database
    PG.connect(dbname: DATABASE_NAME)
  rescue PG::ConnectionBad => e
    puts e.message
    exit(1)
  rescue PG::Error => e
    puts e.message
    exit(1)
  end

  def read_expenses
    result = connect_to_database.exec("SELECT * FROM expenses")
    result.each do |tuple|
      columns = [ tuple["id"].rjust(3),
                  tuple["created_on"].rjust(10),
                  tuple["amount"].rjust(12),
                  tuple["memo"] ]
      puts columns.join(" | ")
    end
  rescue PG::Error => e
    puts e.message
    exit(1)
  end

end

command_first_argument = ARGV[0]

new_expense_manager = ExpenseManager.new

case command_first_argument
when 'list' then new_expense_manager.list_expenses
when 'add' then new_expense_manager.add_new_expense(amount, memo)
else
  new_expense_manager.display_help
end